instill-ai/artifact-backend

Dockerfile

Because
- `docker compose  up` from `instill-core` produces an error 
```sh
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
make: *** [latest] Error 1
```
This commit
- Corrects `Dockerfile`. It had originally been copied from `mgmt-backend` but then adjusted based on other services. This commit reconciles the build strategy.

fix: add /bin/sh to Dockerfile

---

.env
Dockerfile
Dockerfile.dev
Makefile

Because
- The `mgmt-backend` Dockerfiles had been copied and used as base but:
- the `pipeline-backend` and `model-backend` versions are more recent
- `mgmt-backend` overrides the code while the other two don't, so they fit better as a base
This commit
- Reworks Dockerfiles with `pipeline-backend` as a model

feat: use dind in Dockerfile

---

pkg/service/service.go
pkg/service/service_test.go

Because
- Pagination metadata is missing in tag list endpoint.
This commit
- Returns the requested page size and index and the total tag count.

fix: return pagination in tag list endpoint

---

go.mod
go.sum
pkg/constant/constant.go
pkg/db/migration/000002_create_knowledge_base_table.up.sql
pkg/handler/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go
pkg/repository/tag.go
pkg/service/service.go

Because
users need to operate the knowledge base
This commit
provide to crud of knowledgebase
Note:
this commit for poc test. later may need refactor to follow the convention

feat(kb): knowldge base crud endpoints

---

pkg/customerror/error.go
pkg/handler/errors.go
pkg/handler/knowledgebase.go
pkg/middleware/interceptor.go
pkg/repository/knowledgebase.go

Because
using more semantic grpc code to map into http code
This commit
implement corresponding error so that the error interceptor can work

refactor(artifact): using grpc error code

---

cmd/main/main.go
pkg/minio/minio.go

Because
we need more minio connection info when fails
This commit
adds the log

chore(kb): add minio debug log

---

cmd/main/main.go

Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- Uses camelCase for HTTP bodies.

feat: use camelCase for HTTP body

---

.gitignore
pkg/handler/knowledgebasefiles.go
pkg/middleware/interceptor.go

Because
1. no enough message when panic
2. existing file err does not be caught cause nil pointer
This commit
1. use debug print
2. catch the dupliacte file error

chore(kb): add error check

---

pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebasefile.go
pkg/repository/knowledgebasefile_test.go
pkg/worker/worker.go

Because
we need to prevent no-stop loop for failing file process
This commit
add fail status when error happen and not fetch fail status file into embedding process

feat(kb): dealing with failure in file-to-embedding process

---

pkg/db/migration/000005_add_creator_column_to_knowledge_base_tables.up.sql

Because
there are some old data already, it cause new colum cannot be not null without default
This commit
remove not null

fix(kb): fix db migration error

---

pkg/milvus/milvus.go

Because
when there is no similar chunks in milvus. the zero chunks array  incures error. 
This commit
return empty chunk array instead of error

fix(kb): empty similar chunks

---

pkg/handler/knowledgebase.go

Because
it was counted by creator UID
This commit
use the namespace uid to count the catalogs

fix(catalog): max 3 catalog per namespace

---

pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/milvus/milvus.go
pkg/milvus/milvus_test.go
pkg/minio/knowledgebase.go
pkg/minio/minio.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/convertedfile.go
pkg/repository/embedding.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
when user delete the catalog or file, we need to also delete related-artifact. i.e. converted file, chunks, and embeddings
This commit
implements above

fix(catalog): when delete catalog and file, also delete the artifact

---

pkg/milvus/milvus.go

Because
user may not know how to use topk parameter.
This commit
mke topK default 5 when it is not provided.

feat(catelog): make topK default 5

---

go.mod
go.sum
pkg/service/retrieval.go

Because
topk is not precise
This commit
changes topk to topK

fix(catalog): fix topk to topK

---

pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/service/mgmt.go
pkg/service/utils.go

Because
when creating catalog-related, we have limit for different tier
This commit
add check tier logic in catalog max number and total fie storage.
NOTE: in the future, we should remove the tier-related code in CE.

feat(catalog): check the user tier for catalog limit

---

go.mod
go.sum
pkg/acl/acl.go
pkg/client/grpc/pipeline_test.go
pkg/constant/constant.go
pkg/handler/qa.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go
pkg/service/retrieval.go
pkg/worker/worker.go

Because
we need to support question answering
This commit
implement question answering

feat(catalog): support question answering

---

pkg/acl/acl.go
pkg/handler/chunks.go
pkg/handler/knowledgebase.go

Because
chunks some time change
This commit
sorts the chunk by in-order before return

feat(catalog): sort the chunk

---

pkg/repository/knowledgebasefile.go

Because
supprot order asc in create time
This commit
add order when retrieving catalog files

feat(catalog): order asc in create time

---

go.mod
go.sum

Because
catalog needs to use the latest proto-go to have up to date endpoint
This commit
basically just update the proto-go lib

feat(catalog): update the proto-go

---

go.mod
go.sum

Because
the artifact proto is out of date
This commit
use the correct version

fix(artifact): use correct version of proto

---

cmd/main/main.go
go.sum
pkg/client/grpc/pipeline_test.go
pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebasefile.go
pkg/repository/knowledgebasefile_test.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because 
the chunk-to-embedding process is too slow
Commit 
sends concurrent requests to the embedding pipeline, with a batch size of 32 per request.

feat(catalog): support concurrent text to embedding process

---

cmd/main/main.go
pkg/minio/knowledgebase.go
pkg/minio/minio.go
pkg/service/pipeline.go
pkg/usage/usage.go
pkg/utils/utils.go
pkg/worker/worker.go

Because
a goroutine's panic can cause the main process to crash.
This commit
wraps the goroutine in a goRecover function, which adds defer recover.

refactor: wrap goroutines into goRecover

---

pkg/handler/knowledgebasefiles.go

Because
using http ctx will make subsequent goroutine cancled when http response. 
This commit
use new ctx.

fix(artifact): fix ctx issue

---

cmd/main/main.go
pkg/handler/catalog.go
pkg/handler/chunks.go
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/logger/logger.go
pkg/minio/minio.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/convertedfile.go
pkg/repository/knowledgebase.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go
pkg/utils/utils.go

Because
deleting a catalog with too many or huge files will be extremely slow. 
This commit
makes the deletion in the background and marks the catalog as deleted.

fix(artifact): improve catalog deletion slow issue

---

pkg/repository/chunk.go
pkg/repository/embedding.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
1. when all processing workers are busy, the dispatch worker continues to send tasks to the queue. These tasks are not held by any workers, so the dispatcher may keep sending the same tasks to the queue. 
2. when chunk text is empty, it still insert into db.
This commit
1. **Add a check at the beginning of each process step** to verify the file’s processing state in the database. If the state does not matches the current process state, discard the file process task.
2. **Set buffer of worker queue to zero** to prevent out of date file status being queued
3. **Skip the chunk's text if it text is empty**

fix(artifact): fix retry file process

---

pkg/service/pipeline.go

Because
We need more information to indicate the error.
This commit
Adds a response from the pipeline when an error occurs.

feat(artifact): add response from pipeline when calling fails

---

go.mod
go.sum
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/service/chunk.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
1. The document is going to support CSV files, which means we can allow users to upload CSV files into the catalog.
2. When the pipeline call fails, the pipeline info is not saved yet.
This commit
1. Supports the CSV file type 
2. Moves the pipeline info saving process before calling the pipeline.

feat(artifact): support csv file type upload and some improvements

---

pkg/acl/acl.go
pkg/handler/knowledgebasefiles.go
pkg/handler/knowledgebasefiles_test.go
pkg/milvus/milvus.go
pkg/minio/knowledgebase.go
pkg/minio/minio.go
pkg/service/mgmt.go
pkg/service/pipeline.go
pkg/usage/usage.go
pkg/worker/worker.go

Because
- we need to increase stability of using minIO and milvus.
- we need to provide user friendly error message when file name is too long.
This commit
- add retry for calling them
- add custom file name check and return better error message

feat(artifact): add retry in minIO and milvus

---

pkg/minio/knowledgebase.go

Because
when uploading chunks will cause too many concurrent request to minIO
This commit
add rate limit.

fix(artifact): add simple rate limiting to use minIO

---

pkg/minio/knowledgebase.go
pkg/service/pipeline.go

Because
artifact need more error message to debug
This commit
add calling pipeline's metadata to error message

feat: add pipeline metadata in error message

---

pkg/service/mgmt.go
pkg/service/pipeline.go

Because:
- There is a typo in 'enterprise'.
- Sometimes the chunk pipeline returns an empty chunk.
This commit:
- Corrects the typo.
- Filters out the empty chunks.

fix: ignore empty chunk from  chunk pipeline

---

pkg/service/retrieval.go

Because
the embedding pipleine can not allow empty text.
This commit
check the text prompt and throw the better understanding error message

feat: add check on text prompt

---

go.mod
go.sum
pkg/db/migration/000017_create_object_and_object_url_table.up.sql
pkg/minio/main_test.go
pkg/minio/minio.go
pkg/minio/object.go
pkg/minio/object_test.go
pkg/repository/object.go
pkg/repository/objectUrl.go
pkg/service/object.go

Because
the get-object-upload-url handler requires the foundational service library, 
This commit 
implements GetUploadURL.

feat(blob): implement GetUploadURL in service lib

---

config/config.yaml
go.mod
go.sum
pkg/db/migration/000018_add_external_metadata_in_kb_file_table.down.sql
pkg/db/migration/000018_add_external_metadata_in_kb_file_table.up.sql
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/worker/worker.go

Because
when an external service uploads a file, it includes specific metadata for the file. It also needs to check this metadata during the next retrieval.
This commit
allows external_metadata in the file upload API and returns the metadata in the file list API.

feat(catalog): allow external service to store file metadata

---

pkg/service/pipeline.go

Because
the new pipleine is not ready
This commit
revert to the old one for this moment

feat: revert the converting pipeline

---

pkg/service/pipeline.go
pkg/worker/worker.go

Because 
our original converting pipeline is not versatile enough for some complex documents. 
This commit 
adopts the advanced pipeline using VLM.

feat(artifact): adopt the advanced converting pipeline

---

pkg/service/pipeline.go
pkg/worker/worker.go

Because
there is a bug original file process for html
This commit
update the html file process

fix(artifact): update htlm file process

---

config/config.go
config/config.yaml
pkg/service/object.go

Because
for easy usage of our blob service, object url needs the domain
This commit
add the domain in url

feat(blob): add domain in objecturl

---

go.mod
go.sum
pkg/handler/chunks.go
pkg/handler/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go
pkg/repository/knowledgebasefile.go
pkg/service/permission.go

Because
chat ui needs to search chunks and sources
This commit
implements the endpoints

feat(artifact): implement search chunks and sources

---

cmd/main/main.go
pkg/handler/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go
pkg/worker/common.go
pkg/worker/persistentcatalogworker.go
pkg/worker/tempcatalogworker.go

Because
in one min impact, user need a fast indexing mechanism.
This commit
implements the certain workers operating fast indexing for temporary catalog.

feat(artifact): implement fast indexing for temporary catalog

---

pkg/service/pipeline.go

Because
there is a bug in pipeline
This commit
try to use latest version of pipleine for indexing

fix(artifact): fix advanced index pipeline

---

config/config.yaml
pkg/db/migration/000020_remove_idx_unique_encoded_url_path.down.sql
pkg/db/migration/000020_remove_idx_unique_encoded_url_path.up.sql
pkg/mock/repository_i_mock.gen.go
pkg/repository/objectUrl.go
pkg/service/object.go

Because
the high concurrent requests will hit the unique index constrain.
This commit
remove the constrain and use transaction .

fix(blob): fix concurrently create url issue

---

go.mod
go.sum
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go

Because
In a single minute, the user can move a file from one catalog to another.
This commit
Implements the endpoint.

feat(artifact): add move file endpoint

---

pkg/service/preset/pipelines/indexing-advanced-convert-doc/v1.3.1/recipe.yaml
pkg/service/preset/pipelines/indexing-convert-pdf/v1.1.1/recipe.yaml
pkg/service/preset/pipelines/indexing-embed/v1.1.0/recipe.yaml
pkg/service/preset/pipelines/indexing-split-markdown/v2.0.0/recipe.yaml
pkg/service/preset/pipelines/indexing-split-text/v2.0.0/recipe.yaml
pkg/service/preset/pipelines/retrieving-qna/v1.2.0/recipe.yaml

This commit
- renames `format` to `type` in preset pipelines

chore(preset): rename `format` to `type` in preset pipelines

---

Dockerfile.dev
cmd/main/main.go
config/config.go
config/config.yaml
go.mod
pkg/handler/minio.go
pkg/handler/private.go
pkg/handler/public.go

Because
- To improve user data protection, we need to trace who performed each action on MinIO objects.
This commit
- Exposes a private endpoint to ingest MinIO's audit logs and log the relevant information.
- Related: instill-ai/x/pull/36

feat(minio): emit MinIO audit logs in service logs

---

.github/workflows/images.yml
Dockerfile
cmd/main/main.go
pkg/minio/minio.go

Because
- We want to trace the origin or MinIO actions.
This commit
- Adds the service name and version to the MinIO request headers.
- For the moment it doesn't add the authenticated user that's triggering the request. This will be achieved more easily by leveraging the `x/minio` client.

feat(minio): add service name and version to MinIO requests

---

Dockerfile
cmd/main/main.go
config/config.go
config/config.yaml

Because
- We want to always print the MinIO audit logs. If we make this behaviour
configurable, it'll be after it's released and verified.
This commit
- Remove config variable to toggle MinIO webhook behaviour.

chore(minio): always print audit logs

---

pkg/db/migration/000021_rename_content_and_add_chunk_type.up.sql
pkg/milvus/milvus.go

Because
- collections does not support adding new fields, and similarity search should support collections without metadata
This commit
- support metadata-less embeddings search

fix(search): support metadata-less embeddings search

---

pkg/handler/minio.go
pkg/handler/minio_test.go

Because
- In order to set up alerts for uncontrolled data user access, [ILM expiry](https://min.io/docs/minio/linux/reference/minio-server/settings/ilm.html?minio[query]=ilmexpiry&minio[refinementList][platform][0]=linux) rules create noise, as they come from MinIO and don't have access key or agent. 
This commit
- Filter out `ILMExpiry` actions from MinIO logs.

chore(minio): exclude ILMExpiry actions from audit logs

---

pkg/handler/knowledgebase.go

Because
- FE has scenario that requires random catalog id
This commit
- support optional id

chore(catalog): support optional id

---

pkg/repository/chunk.go

Because
- An incorrect TextChunk causes the DB to perform a redundant full table scan. Since the query returns results that are never used, we can skip it entirely if it’s not needed.
This commit
- Prevents the unnecessary full table query.

fix(chunk): prevent the full table query

---

pkg/worker/persistentcatalogworker.go

Because
- The VLM pipeline works better for PPT/PPTX files compared to using the Docling model.
This commit
- Uses the VLM pipeline to convert PPT/PPTX files.

fix(artifact): use VLM pipeline to convert ppt/pptx files

---

pkg/service/pipeline.go
pkg/worker/persistentcatalogworker.go

Because
- The artifact API is going to take a parameter to select the pipeline
that will be used for document conversion.
This commit
- Removes the model conversion method for documents.

chore(kbfile): do not convert files using Docling model

---

.github/workflows/images.yml

Because
- We have updated the login credentials from drop@instill.tech to drop@instill-ai.com in dockerhub.
This commit
- update the dockerhub credentials and docker version  in ga workflow

ci(workflow): update the dockerhub credentials and docker version in ga workflow

---

pkg/service/preset/pipelines/indexing-advanced-convert-doc/v1.3.1/recipe.yaml
pkg/service/preset/pipelines/indexing-convert-pdf/v1.1.1/recipe.yaml

Because
- the pdfplumber converter is not robust.
This commit
- use Docling converter in document component

fix(preset): use docling converter in document component

---

pkg/service/pipeline.go
pkg/service/preset/pipelines/parsing-router/v1.0.0/recipe.yaml

Because
- Sometimes Docling model will be offline and we want to yield a result
(even if sub-optimal) in that scenario.
This commit
- Makes the `parsing-router` pipeline execute the heuristic method
regardless the routing output.
- Uses the heuristic output as the default conversion result, then
checks for the results of the routed method.

chore(conversion): fallback to heuristic method on parsing-router pipeline

---

pkg/milvus/milvus.go

Because
- The current similar vector search is incompatible with legacy
collections.
This commit
- Retrieves the `file_uid` field only if present in the collection schema.

fix(milvus): retrieve file_uid metadata only when present in schema

---

pkg/service/object.go

Because
- base64.StdEncoding might generate `/` in the Base64 string, which can break the structure of the generated blob URL.
This commit:
- Uses base64.URLEncoding to encode the blob URL.

fix(service): use base64.URLEncoding to encode the blob URL

---

pkg/minio/minio.go
pkg/service/object.go

Because
- the object metadata was not correct when returning the object download link.
This commit
- fixes the wrong object metadata.

fix(service): fix the wrong object size

---

.github/workflows/integration-test.yml
go.mod
go.sum

Because
- the `x` package has a major update to catch up
- the latest instrument logic in the `x/client` and `x/server` package can be easily adopted. 
This commit
- upgrade `x` package
- fix a minor CI step error.

ci(deps): upgrade x package

---

go.mod
go.sum
pkg/service/mgmt.go
pkg/service/service.go

Because
- `mgmt`'s API has updated the enum values for the subscription statuses
This commit
- Removes the free plan enum from the client and, instead, interprets
the zero value or the paid plans with non-active statuses as the free
plan.

chore(mgmt): use new subscription states

---

pkg/service/mgmt.go

Because
- The condition in GetNamespaceTier didn’t handle the unspecified plan.
This commit
- Ensures that users without a tier will fall back to TierFree.

fix(service): the user without tier will fallback to TierFree

---

go.mod
go.sum
pkg/handler/qa.go
pkg/handler/retrieval.go
pkg/milvus/milvus.go
pkg/milvus/milvus_test.go
pkg/minio/knowledgebase.go
pkg/repository/objectUrl.go
pkg/service/object.go
pkg/service/retrieval.go
pkg/service/vector.go
pkg/worker/persistentcatalogworker.go

Because
- We want to filter similar chunks by more than one file UID
This commit
- Indexes embeddings by file UID
- Takes a file UID list as a parameter in similarity search (and question
answering)
- Removes the file UID and filename params in the similarity search
endpoint.

feat(embedding): filter embedding search with file UID list

---

pkg/handler/knowledgebasefiles.go

Because
- uploaded filename suffix can possibly be uppercase.
This commit
- introduces an adapter logic for both lowercase and uppercase filename suffix.

fix(catalog): fix uploaded filename suffix uppercase issue

---

integration-test/rest-public.js

This commit
- Checks the summary field is not empty instead of being > 0 in the
processed file integration tests.

fix(integration-test): fix file summary check 

---

pkg/usage/usage.go

Because
- The `TriggerSingleReporter` method was missing the same error filtering logic that exists in `NewUsage` and `StartReporter` methods
- When `GetUserAdmin` fails with "users/admin" error, it should be treated as a debug message rather than an error since only Instill Core CE has the default "admin" user
- Without this filtering, false alarm errors were being logged when the admin user doesn't exist in other Instill editions
This commit
- Adds the same error filtering pattern to `TriggerSingleReporter` that already exists in `NewUsage` and `StartReporter`
- Changes the error handling to check if the error contains "users/admin" and treats it as a debug log instead of an error log
- Ensures consistent error handling across all three methods when dealing with the default admin user …

fix(usage): add missing error filtering for users/admin

---

pkg/handler/knowledgebase.go
pkg/milvus/milvus.go
pkg/minio/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/convertedfile.go
pkg/repository/embedding.go
pkg/service/vector.go
pkg/worker/common.go
pkg/worker/persistentcatalogworker.go

Because
- When reprocessing a file, some leftover data from the previous process
remained, using up space and polluting the vector search
- Embeddings and chunks in database
- Converted files and chunks in blob storage
- Embeddings in vector database.
This commit
- To simplify the cleanup task, blobs are stored under the file UID
prefix (i.e., `{kbUID}/converted-file/{convertedFileUID}` -> `{kbUID}/converted-file/{sourceFileUID}/{convertedFileUID}`).
- Converted file and chunk blobs are deleted by prefix after the new
ones have been generated but before they're inserted.
- The chunks weren't being deleted in the database, now they're
deleted by file UID instead of by source table + UID.
- Embeddings are deleted from the vector database via the file UID
metadata.
- Embeddings were being …

fix(reprocess): clean up data from previous file processing
