instill-ai/artifact-backend

pkg/handler/knowledgebasefiles.go
pkg/minio/minio.go

Because
ListUserAdmin's filter does not work
This commit
Use the GetUserAdmin and GetOrganization as workaround.
Note:
Once mgmt supports getOwnerByID, then we can optimize it.

fix(kb): get owner uid

---

cmd/main/main.go
config/config.yaml
pkg/db/migration/000007_create_text_chunk_table.up.sql
pkg/db/migration/000008_create_embedding_table.up.sql
pkg/handler/knowledgebasefiles.go
pkg/milvus/milvus.go
pkg/minio/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/embedding.go
pkg/repository/knowledgebasefile.go
pkg/worker/worker.go

Because
there are some bugs in chunk process
This commit
fix them

fix(kb): issue of chunking

---

.gitignore
pkg/client/grpc/pipeline_test.go
pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/convertedfile.go
pkg/repository/embedding.go
pkg/repository/embedding_test.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
1. wronng source table and uid
2. wrong destinaiton
3. fail to save vector type in db
This commit
fixed the bug above

fix(kb): fixed some bugs in file-to-embedding process

---

cmd/main/main.go
config/config.yaml
go.mod
go.sum
pkg/db/migration/000010_add_file_size__in_kb_file_table.down.sql
pkg/db/migration/000010_add_file_size__in_kb_file_table.up.sql
pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/knowledgebasefile.go

Because
file catalog need to show file size, tokens #, and chunks #.
This commit
add those info in file list api

feat(kb): add file metadata

---

.env
.gitignore
go.mod
pkg/handler/chunks.go
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go

Because
we are going to provide chunk catalog page
This commit
implemented the chunk related APIs

feat(KB): chunk catalog api

---

.gitignore
go.mod
go.sum
pkg/client/grpc/pipeline_test.go

Because
there is new ptoto go libs
This commit
update the go proto lib

chore(artifact): update protogen-go

---

config/config.yaml
pkg/db/migration/000011_add_kb_file_uid_in_chunk_table.down.sql
pkg/db/migration/000011_add_kb_file_uid_in_chunk_table.up.sql
pkg/db/migration/000012_add_kb_uid_and_kb_file_uid_in_embedding_table.down.sql
pkg/db/migration/000012_add_kb_uid_and_kb_file_uid_in_embedding_table.up.sql
pkg/handler/knowledgebase.go
pkg/handler/retrieval.go
pkg/milvus/milvus.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/chunk.go
pkg/repository/embedding.go
pkg/repository/knowledgebasefile.go
pkg/service/retrieval.go
pkg/worker/worker.go

Because
we would like user using our chunka retrieval api in their own product
This commit
implement chunk retrival api using milvus's similar vector search

feat(kb): retrieval test api

---

config/config.yaml
pkg/db/migration/000013_add_usage_column_in_kb_table.down.sql
pkg/db/migration/000013_add_usage_column_in_kb_table.up.sql
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go

Because
we need to limit the user's resource to prevent from unexpected issue
This commit
1. limit 15 mb file each
2. limit 3 KBs
3. limit 1G per KB

feat(kb): add resource limit

---

pkg/handler/knowledgebasefiles.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go
pkg/service/retrieval.go

Because
need to fix the wrong parameter in similarity chunk search API
This commit
fix it

fix(kb): use correct kb uid in chunk similarity search

---

pkg/client/grpc/pipeline_test.go
pkg/milvus/milvus.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
using preset's pipeline
This commit
integrate with pipleine service

feat(kb): using preset's pipeline for file-to-embedding worker

---

pkg/handler/retrieval.go
pkg/service/retrieval.go

Because
there is bug using owner uid
This commit
fix the bug

fix(kb): similar chunk search by prompt text

---

pkg/handler/chunks.go
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go

Because
1. there are some out of date comment
2. wrong permission check
This commit
fix above

chore(kb): fixed some comment and wrong permission check

---

Makefile
pkg/acl/acl.go

Because
lack in panic message
This commit
add panic message

feat(kb): add check and clear message in openfga init

---

pkg/handler/retrieval.go
pkg/milvus/milvus.go
pkg/service/retrieval.go

Because
1. we wanna monitoring the latency of retrieval test in easy way
2. we wanna enable retrievable button of chunks
This commit
1. add temporary log
2. add the logic to skip the unretirevable chunk

feat(artifact): use retrievable to decide if chunk can be return

---

Makefile
go.mod
go.sum
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/handler/retrieval.go
pkg/service/retrieval.go

Because
we need to rename kb to catalog
This commit
change naming of the kb to catalog

feat(catalog): rename endpoint from kb to catalog

---

pkg/service/pipeline.go

Because
pipleine has limit size of batch, it causes calling embedding pipeline failed.
This commit
limits the max batch size to 32

fix(catalog): call embedding with max 32 size batch

---

pkg/repository/knowledgebasefile.go

Because
page token does not work properly
This commit
fixes the page token issue

fix(catalog): list file api's page token

---

.gitignore
pkg/handler/knowledgebasefiles.go

Because
catalog needs to support more file types
This commit
supports more type in upload file api

feat(catalog): support more file type to uplaod

---

pkg/handler/chunks.go
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
catalog need to suuport instill-format
This commit
allows user to upload and process file types: html, doc, docx, ppt, and pptx.

feat(catalog): support different file-to-embedding process

---

config/config.yaml
pkg/client/grpc/pipeline_test.go
pkg/db/migration/000014_add_requester_column_in_kb_file_table.down.sql
pkg/db/migration/000014_add_requester_column_in_kb_file_table.up.sql
pkg/handler/knowledgebasefiles.go
pkg/handler/qa.go
pkg/handler/retrieval.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebasefile.go
pkg/worker/worker.go

Because
when calling pipeline, it requires requester
This commit
add requester in pipeline call

fix(catalog): add requester when calling pipeline

---

pkg/handler/catalog.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebasefile.go
pkg/repository/knowledgebasefile_test.go
pkg/service/chunk.go
pkg/service/pipeline.go
pkg/service/retrieval.go
pkg/worker/worker.go

Because
artifact backend needs to support file catalog api
This commit
implements it

feat(catalog): add file catalog api

---

pkg/acl/acl.go
pkg/acl/acl_test.go
pkg/handler/knowledgebase.go

Because
sometime the acl get deleted before catalog deletion
This commit
changes move the acl deletion behind the catalog deletion.

fix(catalog): fix the catalog permission issue

---

.gitignore
go.mod
go.sum
pkg/client/grpc/pipeline_test.go
pkg/handler/knowledgebase.go
pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/service/chunk.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
catalog needs to support xlsx
This commit
support xlsx

feat(catalog): support xlsx

---

pkg/acl/acl.go

Because
better comment can help to understand the acl code
This commit
add some comments on primary acl functions

chore(catalog): add comment on acl function

---

pkg/handler/qa.go
pkg/service/pipeline.go

Because
there is new version of question answering pipeline
This commit
updated the pipeline that used by artifact

feat(catalog): update the pipeline that ask endpoint use

---

pkg/handler/catalog.go

Because
the get-file-catalog API needs to support returning the original file data
This commit
enables the API to return the original file data using base64 encoding.

feat(catalog): support originalData return

---

Makefile
pkg/handler/knowledgebasefiles.go
pkg/worker/worker.go

Because
minIO sometime not stable and file deletion take too long
This commit
1. add minIO retry
2. move time-consuming deletion into goroutine

feat(artifact): add minIO retry and file deletion

---

pkg/handler/knowledgebasefiles.go
pkg/repository/knowledgebasefile.go
pkg/service/chunk.go
pkg/service/pipeline.go
pkg/worker/worker.go

Because
we need to support xls file type in catalog
This commit
add xls support

feat(artifact): support xls

---

pkg/client/grpc/client.go
pkg/client/grpc/mgmt.go

Because
need higher max payload size for file process
This commit
increase up to 256 MB

fix: increase max payload size

---

pkg/minio/minio.go

Because
there is a random output of minIO
This commit
add index for concurrent requests

fix(artifact): fix minio "get file by path"

---

go.mod
go.sum
pkg/handler/object.go
pkg/service/object.go
pkg/service/utils.go
pkg/utils/mime.go
pkg/worker/worker.go

Because
artifact will start to provide the object upload url
This commit
implements the handler

feat(blob): provide the upload object url endpoint

---

go.mod
go.sum
pkg/db/migration/000017_create_object_and_object_url_table.up.sql
pkg/handler/object.go
pkg/handler/private.go
pkg/middleware/interceptor.go
pkg/minio/object.go
pkg/minio/object_test.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/object.go
pkg/repository/objectUrl.go
pkg/service/object.go
pkg/service/utils.go

Because
blob refactor will make artifact able to presign the url so that console to get the url for uploading and downloading
This commit
implement it

feat(blob): provide blob url endpoint

---

pkg/service/pipeline.go
pkg/worker/worker.go

Because
- The current embedding processing system lacks proper concurrency control, which could lead to resource exhaustion when processing large batches of texts
- Large embedding batches being processed all at once could cause timeouts and system instability
- The code lacks comprehensive documentation for complex processing functions
- Error handling and logging for embedding operations needed improvement
This commit
- Adds concurrent processing limits (max 5 goroutines) to the `EmbeddingTextPipe` function to prevent resource exhaustion
- Implements batch processing (50 items per batch) in `saveEmbeddings` to handle large volumes of embeddings more reliably
- Enhances error handling and logging throughout the embedding pipeline
- Adds detailed documentation for key functions:
- …

perf(catalog): enhance the stability of embeddings saving

---

config/config.yaml
go.mod
go.sum
pkg/db/migration/000019_refactor_kb_for_chat.down.sql
pkg/db/migration/000019_refactor_kb_for_chat.up.sql
pkg/handler/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go

Because
chat need the ephemeral catalog
This commit
support ephemeral catalog

feat(artifact): support ephemeral catalog

---

pkg/minio/minio.go

Because
- MinIO init function logs could be more descriptive and aligned with `instill-ai/x/minio`
This commit
- Updates the MinIO client creator function.

chore(minio): improve init function logging

---

cmd/main/main.go
config/config.go
config/config.yaml
go.mod
go.sum
pkg/client/grpc/model.go
pkg/constant/constant.go
pkg/handler/knowledgebase.go
pkg/repository/knowledgebasefile.go
pkg/service/model.go
pkg/service/service.go
pkg/service/service_test.go
pkg/worker/persistentcatalogworker.go
pkg/worker/tempcatalogworker.go

Because
- host docling model in Instill Model with CUDA acceleration
This commit
- support instill model in doc conversion process

feat(conversion): support instill model in doc conversion process

---

pkg/handler/knowledgebase.go
pkg/service/model.go
pkg/service/pipeline.go
pkg/worker/persistentcatalogworker.go

Because
- docling model might not be deployed under circumstances
This commit
- add fallback mechanism for unavailable model

feat(conversion): add fallback for unavailable model

---

go.mod
go.sum
pkg/handler/knowledgebasefiles.go
pkg/minio/minio.go
pkg/repository/objectUrl.go
pkg/worker/persistentcatalogworker.go
pkg/worker/utils.go

Because
- catalog file has not adopt blob upload/download
This commit
- support blob upload/download for catalog file

refactor(artifact): support blob upload/download for catalog file

---

go.mod
go.sum
pkg/handler/knowledgebasefiles.go
pkg/handler/retrieval.go

Because
- Agent requires file summary for RAG
This commit
- implement get summary endpoint

feat(artifact): implement get summary endpoint

---

go.mod
go.sum
pkg/handler/knowledgebasefiles.go

Because
- we need a new GetCatalogFile endpoint to let user get file information.
This commit
- implements GetCatalogFile endpoint.
- add summary and download_url in File object.

chore(artifact): implement GetCatalogFile endpoint

---

pkg/handler/knowledgebasefiles.go

This commit
- fix embedded downloadURL bug in the file response

fix(handler): fix embeded downloadURL bug

---

pkg/service/pipeline.go
pkg/worker/persistentcatalogworker.go

Because
- the non-document files such as csv can not be processed.
This commit
- resolves the issue where non-document files cannot be processed

fix: resolve the issue where non-document files cannot be processed

---

go.mod
go.sum
pkg/service/mgmt.go

This commit
- Updates the enum value for the subscription from PRO to STARTER

fix(subscription): update enum for starter plan

---

pkg/handler/knowledgebasefiles.go

Because
- Files uploaded to artifacts using the legacy method cannot generate download links.
- Legacy flow: files are uploaded directly to the instill-ai-knowledge-bases bucket.
- New flow: files are uploaded directly to the instill-ai-blob bucket and then referenced in the artifact.
This commit
- Fixes the issue by re-uploading files from the knowledge base bucket to the blob storage bucket, aligning them with the new upload flow.

fix(handler): fix the empty download link for files uploaded in legacy way

---

go.mod
go.sum
pkg/handler/knowledgebase.go
pkg/mock/repository_i_mock.gen.go
pkg/repository/knowledgebase.go

This commit
- Allows users to modify the conversion pipelines of a catalog.

feat(catalog): specify document conversion pipelines in catalog update

---

pkg/handler/knowledgebasefiles.go

This commit
- fixes wrong IsUploaded check.

fix(handler): fix wrong IsUploaded check
